sudo: required
services: 
    - docker
before_install:
    - docker build -t katja1909/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run katja1909/react-test npm test -- --coverage 
after_success:
# Production versions of each container
# 1. build images of each container 
# docker build -t <docker user name>/<image name(tbd)> <context> 
    - docker build -t katja1909/fibonacci-client ./client
    - docker build -t katja1909/fibonacci-nginx ./nginx
    - docker build -t katja1909/fibonacci-server ./server
    - docker build -t katja1909/fibonacci-worker ./worker
# Log in to the docker CLI (for that first define environment variables 
# on dockerhub -> your project -> more options -> settings)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
    - docker push katja1909/fibonacci-client
    - docker push katja1909/fibonacci-nginx
    - docker push katja1909/fibonacci-server
    - docker push katja1909/fibonacci-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: fibonacci-docker-aws
    env: FibonacciDockerAws-env
    bucket_name: elasticbeanstalk-us-east-2-474934949302
    bucket_path: docker-fibonacci
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

